config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'

 get 'profiles/:id' => 'profiles#show', as: :profile
 get 'profiles' => 'profiles#index'

  resources :relationships

  resources :tweets do
    resources :likes
end

  devise_for :users

  root 'tweets#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tweet
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base

  belongs_to :user
  has_many :likes

  validates :message, presence: true,
                      length: { maximum: 140,
                                too_long: 'A tweet is only 140 characters max. Everybody knows that!'
                              }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :tweets
         has_many :relationships
         has_many :friends, through: :relationships

         has_many :inverse_relationships,  class_name: "Relationship",                                foreign_key: "friend_id"
         has_many :inverse_friends, through: :inverse_relationships, source: :user

         has_many :likes

         def likes?(tweet)
           tweet.likes.where(user_id: id).any?

         end

  validates :username, presence: true
  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

before_action :configure_permitted_parameters, if: :devise_controller?

protected

def configure_permitted_parameters

  devise_parameter_sanitizer.permit(:sign_up) { |u|
      u.permit( {roles: [] },
                 :email,
                 :password,
                 :password_confirmation,
                 :name,
                 :username,
                 :bio,
                 :location )
    }
  devise_parameter_sanitizer.permit(:account_update) { |u| u.permit( :email, :password, :password_confirmation, :current_password, :name, :username, :bio, :location ) }

 end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tweet

  def create
    @tweet.likes(where(user_id: current_user.id).first_or_create

    respond_to do |format|
      format.html { redirect_to request.referrer }
    end
  end

  def destroy
    @tweet.likes.where(user_id: current_user.id).destroy_all

    respond_to do |format|
      format.html { redirect_to request.referrer }
    end
  end

  private

  def set_tweet
    @tweet = Tweet.find(params[:tweet_id])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
     #This sets @user to a user based on their id
  @user = User.find(params[:id])
  end

  def index
    #This sets @users to every User in our database
  @users = User.all
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @relationship = current_user.relationships.build(friend_id: params[:friend_id])

    if @relationship.save
      flash[:notice] = "You're now friends!"
      redirect_to profile_path(current_user.id)
    else
      flash[:notice] = "Unable to follow."
      redirect_to root_path
    end
  end

  def destroy
    @relationship = current_user.relationships.find(params[:id])
    @relationship.destroy

    flash[:notice] = "No longer following."
    redirect_to profile_path(current_user.id)
  end

  private

  def relationship_params
    params.require(:relationship).permit(:user_id, :friend_id)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
before_filter :authenticate_user!
before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  def index
    @tweets = Tweet.all
  end

  def show

  end

  def edit

  end

  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { reditect_to @tweet,
                                  notice: 'Your tweet has been updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet Destroy!' }
    end
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet,
                      notice: 'You made a tweet!' }
      else
        format.html { render :new }
      end
    end
  end

  private

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  def tweet_params
    params.require(:tweet).permit(:message, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitterific</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= link_to "Sign Out", destroy_user_session_path,
                          method: :delete,
                          class: 'btn btn-danger btn-xs' %>
    <%= yield %>
  </body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/profiles/index.html.erb
<h1>All Users<h1/>

<% @users.each do |user| %>
  <%= link_to user.username, profile_path(user) %> <br>
<% end %>

app/views/profiles/show.html.erb
<div class="row">
  <div class= "col-xs-4">
  <h3><%= @user.name %></h3>
  <h5><%= @user.username %></h5>
  <h5><p><%= @user.bio %></p></h5>
  <h5><%= @user.location %></h5>
  <h5>Joined on <%= @user.created_at.strftime("%B %Y") %></h5>

  <%= @user.relationships.count %> Following
  <br />
  <% @user.relationships.each do |relationship| %>
    <%=link_to relationship.friend.name, profile_path(relationship.friend) %>
  <%end%>
  <br />
  <br />
  <%= pluralize(@user.inverse_relationships.count, "Follower") %>.
  <br />
  <% @user.inverse_friends.each do |friend| %>
    <%=link_to friend.name, profile_path(friend) %> <br />
  <%end%>
  </div>

  <div class= "col-xs-7">
    <div class="panel panel-default">
      <% @user.tweets.each do |tweet| %>
        <div class="panel-body">
          <strong><%= tweet.user.username %> </strong><small>tweeted <%= time_ago_in_words(tweet.created_at) %> ago</small>
          <br />
          <br />
          <%= tweet.message %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<br />
<br />
<% if current_user.id != @user.id %>
  <% if current_user.friends.include?(@user) %>
    <%= link_to "Unfollow", relationship_path(current_user.relationships.find_by_friend_id(@user)), :method => :delete %>
  <% else %>
    <%= link_to "Follow", relationships_path(:friend_id => @user), method: :post %>
  <% end %>
<% end %>

app/views/shared/_likes.html.erb
<% if current_user.likes?(@tweet) %>
  <%= link_to "Unlike", tweet_likes_path(@tweet), method: :delete %>
<% else %>
    <%= link_to "Like", tweet_likes_path(@tweet), method: :post %>
<% end %>

<%= @tweet.likes.count %>

Liked by:
<% @tweet.likes.each do |like| %>
  <br>
  <%= like.user.username %>
  <br>
<% end %>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <!-- This part checks for errors -->
  <% if @tweet.errors.any? %>
     <div id="error_explanation">
       <h2>
         <%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:
       </h2>

       <ul>
         <% @tweet.errors.full_messages.each do |error| %>
           <li><%= error %></li>
         <% end %>
       </ul>

     </div>
  <% end %>
  <!-- This is the form -->
  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>

  <div class= "actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/tweets/edit.html.erb
<h1>Edit Tweet</h1>

<%= render 'form' %>

<%= link_to 'See All The Tweets Again, if you want too...', tweets_path %>
<br>

app/views/tweets/index.html.erb
<p id= "notice"><%= notice %></p>

<h1>All The Tweets In The Universe!</h1>

<table class="table table-striped table-hover">

  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>


  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.message %></td>
        <td><%= tweet.user.username %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet,
                                   method: :delete,
                                   data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>
<br>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

<%= link_to 'See All The Tweets Again, if you want too...', tweets_path %>
<br>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message: </strong>
  <%= @tweet.message %>
</p>

<p>
  <strong>User: </strong>
  <%= @tweet.user.username %>
</p>

<%= render 'shared/likes' %>
<br>
<%= link_to 'Edit This Tweet', edit_tweet_path(@tweet) %>
<br>
<%= link_to 'See All The Tweets', tweets_path %>
<br>